# Generated by Django 4.2.7 on 2023-11-16 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("issues", "0002_alter_issue_senior"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="junior",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="junior_issues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
