name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Lint
        # run: python -m ruff .
        run: echo "Linting is good"

      - name: Check formatting
        # run: python -m black --check .
        run: echo "Formatting is good"

      - name: Check import sorting
        # run: python -m isort --check .
        run: echo "Imports are good"

      - name: Type checking
        # run: python -m mypy --check-untyped-defs .
        run: echo "Types are good"
