name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name : Lint
        run: python -m ruff .

      - name : Check formatting
        run: python -m black --check .

      - name : Check import sorting
        run: python -m isort --check .

      - name : Type checking
        run: python -m mypy --check-untyped-defs .